---
title: "Visualization Lab 2"
author: "Sports Camp Crew"
date: "June 2019"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: paper
---

Name: Roberto Clemente

---

# Getting familiar with ``ggplot``



Load in the `tidyverse` package and read in the MLB data.

```{R, warning = FALSE, message = FALSE }
library(tidyverse)
mlb <- read.csv("https://raw.githubusercontent.com/ryurko/CMSACamp/master/data/intro_r/mlb_teams_data.csv?token=AFKSV7BGJHKW3W72AMN2K5C453U7Q")
```

## Basics

Perhaps the primary component of the `tidyverse`, `ggplot2` consists of a powerful set of functions used to make useful, interesting, and aesthetically pleasing figures or graphs in a **standard** and **unform manner**.  There are many, many great resources for learning ggplot2 and the philosophy behind it (shown in the "Grammar of Graphics") that are listed below in the references.  We recommend checking them out.

Broadly, the idea behind ``ggplot2` is that different features of plotting form a language where the features have structure and rules associated with them (i.e. a grammar).  The most important part of any `ggplot` is not the plot type you are trying to make (e.g. scatter plot, histogram, dendrogram, barplot, etc.), but the data itself.

## Initializing a plot

More importantly, the data in any `ggplot` is assumed to be a `data.frame` which is a data structure fairly unique to `R`.  You don't have to know a lot about the intricacies of these structures, but just know there are a lot of details just under the surface!

1. Initialize a plot

```{R, warning = FALSE, message = FALSE }
ggplot()
```

**Congratulations**, you have made an empty plot!  In wonky metaphor land, we may say this is the medium on which we are writing our sentences that will become amazing visualizations.

2. Save the plot for later and enter the data.

```{R, warning = FALSE, message = FALSE }
g <- ggplot(data = mlb)
```

Note that the above shows nothing, not even an empty plot.  That is because we have stored the plot itself as a variable!  This is a useful feature because we can save partial plots and add to them dynamically.

3.  Change the data.  We have now changed the data.

```{R, warning = FALSE, message = FALSE}
x <- seq(1, 10, by = 2)
df <- data.frame(x = x, y = 2 * x, z = letters[x],
                 group = rep(c(1,2), length.out = length(x)))
```

**Question 1.** Can you describe, in words, what each of the columns of our new data frame `df`

```{R, warning = FALSE, message = FALSE }
g2 <- ggplot(data = df) 
```

4.  The columns in a `data.frame` are very important for ggplot.  We **map** columns of a data frame to different **aesthetics**, which is abbreviated as `aes()` (and is itself a function) in `ggplot2`.  For example, we commonly talk about plotting "y vs. x."  We can do this directly.

```{R, warning = FALSE, message = FALSE }
g <- ggplot(data = mlb, aes(x = year, y = strikeouts))
g
```

Note that the above plot has assigned the "year" column to the x-axis and "strikesout" to the y-axis.  Also note that the plot does not contain any points.  This is because we have not told the plot how to handle the data, we only labeled what it is.

**Question 2**

5. Set up an empty plot so that instead of strikeouts and year we look at hits (y-axis) vs. sacrifice flies (x-axis).  You can use the `colnames()` function to find the column names that you need.  We put in some code to get you started.

```{R, warning = FALSE, message = FALSE }
## R code here
g3 <- ggplot()
g3
```

6. Finally, we are ready to add to make our data visible.  Fortunately, `ggplot2` contains a plethora of ready-made functions.

```{R, warning = FALSE, message = FALSE }
g2 <- ggplot(data = mlb, aes(x = year, y = strikeouts)) + geom_point()
g2
```

**Question 3**.  Make a scatter plot for `g3` which is hits vs. sacrifice flies.

```{R, warning = FALSE, message = FALSE }
## R code here
```


7.  The beauty of `ggplot` comes from the following: we can make a lot of different plots just by changing one word.  The `geom_*` family is special and the suffix `*` will tell `ggplot2` what to do with our data (provided we have assigned it correctly with `aes()`).

```{R, warning = FALSE, message = FALSE }
## Connecting lines
ggplot(data = mlb, aes(x = year, y = strikeouts)) + geom_line()

## A smooth line
ggplot(data = mlb, aes(x = year, y = strikeouts)) + geom_smooth()

## A smooth line
ggplot(data = mlb, aes(x = year, y = strikeouts)) + geom_rug()

## All together
ggplot(data = mlb, aes(x = year, y = strikeouts)) + geom_point() + geom_line() + geom_smooth() + geom_rug()
```

**Question 4**.  Try out at least two of the `geom_*` functions on the data for hits vs. sacrifice flies.  Try exploring with some more `geom_*` functions [here](https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf).  Are there any that cause an error?

```{R, warning = FALSE, message = FALSE }
## R code here
```

## Presentation

The package ``ggplot2`` does a lot of the heavy lifting when it comes to make interesting plots, given we have the data in the proper structure.  However, it just as important that our plots are **readable**.  Many people (maybe your future boss and definitely your current TAs) like to be able to view figures and graphs as objects that can stand on their own.  This means that we should not have to look elsewhere in the text to understand the **main** ideas your plot is trying to convey.  At a bare minimum this means any plot should have

1. A meaningful title

2. Meaningful axis titles and legend titles

3. One or two clear concepts (as opposed to trying to show everything about your data in one plot **or** being very repetitive in the features shown)

4. Consideration for `data ink` (the concept that if something does not meaningfully contribute to a figure, is it really necessary?)


**Question 5**. Consider the plot shown below.  What can you say about this plot with regards to the 4 criteria listed above?

```{R, warning = FALSE, message = FALSE }
## All together
ggplot(data = mlb, aes(x = year, y = strikeouts)) + geom_point() + geom_line() + geom_smooth() + geom_rug()
```

```
## Answer here
```

Again, fortunately for us, `ggplot` gives us some functions to help with the above.  We also have to use our good judgment.  "Make good decisions" - Anonymous. 

Specifically, we will make use of the `labs()` function and the `theme_*()` functions.  The second will especially become more important as we progress this summer. 

We will also show how we can build the plot dynamically.

```{R, warning = FALSE, message = FALSE}
g <- ggplot(data = mlb, aes(x = year, y = strikeouts)) + geom_point()
g + labs(x = "Year", y = "Strikeouts", 
         title = "Year vs. strikeouts",
         subtitle = "Major League Baseball") +
  theme_bw()
```

**Question 6**.  Create a scatterplot of hits vs. sacrifice flies with better respect to the 4 criteria listed above.  Also add a smooth trend line to the plot.

```{R, warning = FALSE, message = FALSE}
## R code here
```

## 'Bonus' exercises
To come

1. group coloring

2. legends and scales

3. text size and font

4. arranging multiple graphs on a page

5. combining different data sets

## Resources

